---
# tasks file for softwares
- name: "Get {{ item.name }} Script"
  ansible.builtin.get_url:
    url: "{{ item.script }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode }}"
  loop: "{{ curl_packages }}" 

- name: Installing {{ item.name }}
  command: "bash {{ item.dest }}"
  loop: "{{ curl_packages }}"

- name: Installing {{ item }} packages 
  ansible.builtin.apt:
    name: "{{ item }}"
    state: "present"
    update_cache: yes
  loop: "{{ apt_packages }}"
  become: yes

- name: Get the deb package
  ansible.builtin.get_url:
    url: "{{ item.url }}" 
    dest: "{{ item.dest }}"
    mode: '0755'
  loop: "{{ deb_packages }}"

- name: Install the deb package
  ansible.builtin.apt:
    deb: "{{ item.dest }}"
  loop: "{{ deb_packages }}"
  become: yes
 
- name: "Installing {{ item }} packages"
  community.general.snap:
    name: "{{ item.name }}"
    classic: "{{ item.classic }}"
  loop: "{{ snap_packages }}"
  become: yes
  notify: started microk8s

- include_tasks: microk8s.yml

- include_tasks: vscode.yml

- include_tasks: jenkins.yml

- include_tasks: virtualbox.yml

- include_tasks: vagrant.yml