---
# tasks file for softwares
- name: Install apt packages
  ansible.builtin.apt:
    name: "{{ item }}"
    state: "present"
  loop: "{{ apt_packages }}"
  become: yes

- name: Get the deb package
  ansible.builtin.get_url:
    url: "{{ item.url }}" 
    dest: "{{ item.dest }}"
    mode: '0755'
  loop: "{{ deb_packages }}"

- name: Install the deb package
  ansible.builtin.apt:
    deb: "{{ item.dest }}"
  loop: "{{ deb_packages }}"
  become: yes
 
- name: "Installing {{ item }} packages"
  community.general.snap:
    name: "{{ item.name }}"
    classic: "{{ item.classic }}"
  loop: "{{ snap_packages }}"
  become: yes
  notify: started microk8s

- name: Enable microk8s plugins
  command: "microk8s enable {{ item }}"
  loop: "{{ microk8s_plugins }}"
 
